# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                       Darkness Liquidation                                   |
# |                                                                                              |
# |                               Discord: https://dsc.gg/darkness-liquidation                   |
# |                                                                                              |
# |                                 Authors: 1hendex x clopdisabler                              |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# To run Darkness, a license is required (provided upon purchase)
your_license: "null"

alerts:
  # In addition to broadcasting alerts to players, should they also be sent to the console?
  print_to_console: true
  # This controls whether/how alerts are shared between servers connected to your proxy.
  # You must have 'bungee-plugin-message-channel' enabled in your Velocity's configuration if Velocity is in use.
  proxy:
    # Should alerts be sent to other servers connected to your proxy?
    send: false
    # Should the alerts received from other servers be announced to this server?
    receive: false

verbose:
  print_to_console: false

# Should we enable the test mode?
# If this mode is enabled, the punish, rotate, and slot shuffle commands will not work.
test_mode: false

# Client Settings
client_settings:

  # Client Alert Settings
  alert:

    # Should we send an Alert when a player joins specifying his Client Brand?
    enabled: true

    # Removes the following regex from the brand
    remove: " \\(Velocity\\)$"

    # This means it won't broadcast their brand to operators if the brand matches the following regexes
    ignored_clients:
      - "^badlion$"
      - "^optifine$"
      - "^vanilla$"
      - "^fabric$"
      - "^Feather Fabric$"
      - "(^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4}$)|(^lunarclient:[a-z0-9]{7}/[\\w_/-]{3,32}$)"
      - "^labymod$"

  # Client brands containing the following names will be blocked from joining the server
  banned_clients:
    - "^1.12.2$"
    - "^mcp$"
    - "^ForgeOptiFine 1.16.5/forge/modified$"

  # Minimum/Maximum client brand name length.
  symbol_limiter: 5:16
  # Whether to check the number of caps (recommended not to disable to detect client spoofing like FORGE, VANILLA) (-1 to disable)
  caps_percentage: 70
  # Blocking the use of invalid characters in the brand name.
  whitelist_regex: "^[a-zA-Z0-9:_/, .-]+$"
  # Should we block cheat clients by suspicious signs (e.g., Delta Client and others)
  cheat_detector: true
  # Darkness will block clients by brand name using a regex.
  # If the client name matches this regex, it will not be able to join the server.
  payload:
    - "Remix"
    - "CRYSTAL"
    - "matrix"
    - "CrystalWare"
    - "Misplace"
    - "reach"
    - "lmaohax"
    - "Reach Mod"
    - "cock"
    - "Vape v3"
    - "1946203560"
    - "#unbanearwax"
    - "EARWAXWASHERE"
    - "Cracked Vape"
    - "EROUAXWASHERE"
    - "moon:exempt"
    - "Vape"
    - "WDL|INIT"
    - "WDL|CONTROL"
    - "Bspkrs Client"

  # Darkness will blacklist specific Forge versions that include built-in Reach hacks (Forge 1.18.2 â€” 1.19.3).
  # Setting this to false will allow these clients to connect to the server.
  # Use at your own risk.
  disconnect_blacklisted_forge_versions: true

# Packet Settings
packet_settings:

  # Maximum number of skipped transactions before the player is kicked
  # Triggers on FreeCam, BackTrack, Blink
  transaction_skip: 400
  # How much time players have before being kicked for a timeout? Default = 45 seconds
  transaction_time: 45
  # Maximum allowed negative timer offset of the player before kicking (in milliseconds)
  # Triggers on Timer (0.1), Freeze
  negative_timer: 5000
  # This setting applies only to clients 1.17â€“1.20.5 on 1.8 servers
  cancel_duplicate_packet: true
  # Should rotation be ignored in duplicate packets?
  ignore_duplicate_packet_rotation: true
  # Enable this to prevent Darkness from cancelling pong packets received from players
  # Can improve compatibility with other anti-cheats. May cause issues with packet limiters
  # Do not enable this if you are unsure what you are doing
  disable_pong_cancelling: false
  # Darkness sometimes cancels illegal packets, e.g., with Timer, after X cancelled packets per second
  # Should we just kick the player instead? This is needed because some packet limiters donâ€™t account for packets cancelled by Darkness
  packet_spam_threshold: 100

# Punishment command settings // Not recommended for use â€” will be removed soon
point_command:

  # Commands that will be executed under various conditions (e.g., violations)
  '1': darkness rotate %PLAYER%
  '2': darkness shuffle %PLAYER% many
  '3': darkness rotate %PLAYER%
  '4': darkness shuffle %PLAYER% many
  '6': darkness kick %PLAYER% &cSuspicion of using cheats
  '7': darkness crash %PLAYER% particle
  '8': darkness kick %PLAYER% &cSuspicion of using cheats
  '9': darkness ban %PLAYER% &cSuspicion of using cheats
  '21': darkness kick %PLAYER% &cSuspicion of using cheats
  '26': darkness kick %PLAYER% &cSuspicion of using cheats
  '30': darkness ban %PLAYER% &cSuspicion of using cheats
  '34': darkness kick %PLAYER% &cSuspicion of using cheats
  '38': darkness ban %PLAYER% &cSuspicion of using cheats

# Punish Command Settings
punish_command:

  # What Punish Animation Should Darkness display before executing the below command?
  # Animations: NONE, THOR, FIRE, ERROR, SHAME or RANDOM to let it choose a random animation each time
  animation: NONE

  # Should we broadcast in chat when a player gets punished by Darkness?
  broadcast: true

  # What command should Darkness execute once the Punish Animation ends? (%nl% for new line)
  # Placeholders: %prefix% -> (Darkness Prefix), %player% -> (The player that got punished), %reason% -> (The reason provided by the Darkness punish command)
  command: darkness kick %player% %prefix% %reason%

# Punish Wave Settings
punishwave:

  # Should the Punish Wave be enabled?
  # If the Punish Wave is enabled, Darkness will punish all cheaters at once
  # If a player is punished using the /darkness punish command while the Punish Wave is enabled,
  # they will be added to the queue and punished when the Punish Wave starts
  enabled: false

  # Should Darkness broadcast this event?
  broadcast: true

  # How often should the Punish Wave be executed? (in minutes)
  time: 15

  # Countdown before executing the Punish Wave (-1 to disable)
  countdown: 5

# Ban Command Settings
ban_command:

  # Should we broadcast in chat when a player gets punished by Darkness?
  broadcast: true

  # Placeholders: %player% -> (The player that got punished), %reason% -> (The reason provided by the Darkness punish command)
  command: ban %player% %reason%

# Discord Sync Settings
discord:

  # Would you like to Sync Darkness to your Discord Server?
  enabled: false
  # Insert the Channel Webhook URL
  webhook_url: ""
  # Message title
  embed_title: "**:fire: NEW CHEATER DETECTED!**"
  # Color of the stripe on the left side of the message
  embed_color: "#ff0000"
  # Message content
  violation_content:
    - "%player%"
    - ""
    - "ðŸ›¡ï¸ **Server Name:**"
    - "%server_name%"
    - ""
    - "ðŸ“¦ **Cheat Type:**"
    - "%check%"
    - ""
    - "ðŸ“Š **VL**"
    - "%violations%"
    - ""
    - "ðŸ–¥ï¸ **Client:**"
    - "%brand%"
    - ""
    - "ðŸ“Œ **Version:**"
    - "%version%"
    - ""
    - "ðŸ“¶ **PING | TPS:**"
    - "%ping% | %tps%"

  # Would you like Darkness to send Discord Messages
  # When players get punished from the Punish Wave?
  punishwawe: false
  punishwawe_title: "**:fire: A WAVE OF NEW CHEATERS DETECTED!**"
  # Message content
  punishwawe_content:
    - "ðŸ›¡ï¸ **Server**"
    - "%server_name%"
    - ""
    - "ðŸ‘¥ **Players Punished**"
    - "%players_punishwawe%"
    - ""

  # Title of the additional field in the embed
  embed_field: "Information:"

# Log Settings
logs:

  # What type of logging should Darkness use?
  # Types: YAML_ONE, YAML_DAYS, MYSQL, SQLITE, NONE
  # 1. YAML_ONE - Logs all flags into a single file data.yml
  # 2. YAML_DAYS - Logs each day into a separate file inside the logs folder
  # 3. SQLITE - Logs into SQLite database
  # 4. MYSQL - Logs into MySQL database
  # 5. NONE - Disables logging
  # Changes are applied only after a server restart.
  type: YAML_ONE

  # Logs older than this value of Days will be cleared
  clear_days: 7

  # MySQL Settings (Requires MySQL Type)
  mysql:
    host: localhost
    port: 3306
    database: database
    user: root
    password: ''
    use_ssl: false

    # MySQL Connection Pool Settings
    # Do not change unless you know what you're doing
    pool_settings:
      maximum_pool_size: 50
      minimum_idle: 30
      maximum_lifetime: 1800000
      connection_timeout: 30000
      leak_detection_threshold: 0

## InformationHider Check
InformationHider:

  # Enable the info-hiding module?
  enabled: true

  # Check only players or all entities?
  onlyForPlayers: true

  # Hides data about players/mobs to block cheat clients from getting extra info.
  # Regular players won't notice, but cheats will suffer.
  parts:
    # Spoofs health â€” players and mobs always show fake health
    # Useful against health bars in mods and cheats
    health:
      # Specify the value Darkness should spoof for players from 0 to 20.
      # A value of 0 will break many KillAura hacks, but also breaks walking animations.
      # Not recommended if you don't want players to walk like they're "moonwalking".
      value: 20
      # If enabled, a random value from 0 to 20 will be used.
      # Less noticeable to players and better preserves gameplay.
      random: false

    # This module creates fake staff members in the tab list to hide real moderators from cheats.
    # Donâ€™t worry these bots exist only on the client side, real players canâ€™t see them.
    fake_staff:
      # Should we create fake bots to mask real staff members?
      enabled: true
      # If true, Darkness will always generate bots with random names.
      # Helps with compatibility on some servers but can sometimes bypass StaffList checks.
      only_random_name: false
      # Specify the real staff prefixes that will be shown on fake bots.
      roles:
        - "&cAdmin"
        - "&cStaff"
        - "&cHelper"
        - "&cModer"
      # Recommended to set bots >= 60 to prevent cheats from detecting real moderators.
      bots: 60

    # This part hides enchantments to prevent cheats from showing the correct type and level.
    enchant: true
    # This part hides item counts in hands, inventory contents, and equipment to prevent cheats from obtaining accurate item information.
    item_count: true
    # This part hides the real names of items in the player's hands to prevent cheats from obtaining accurate information about them.
    item_name: true
    # This part hides the real names of items on the ground to prevent cheats from obtaining accurate information about them.
    item_drop: true
    # This part hides item durability to prevent cheats from showing the correct durability.
    durability: true
    # This part hides player XP to prevent cheats from showing the exact experience level.
    xp: true
    # This part hides player air to prevent cheats from showing the exact air level.
    air: true
    # This part hides absorption effects to prevent cheats from showing the correct value.
    absorption: true
    # This part hides player saturation to prevent cheats from showing the exact level.
    saturation: true
    # This part hides scoreboard data to prevent cheats from accessing stats information.
    scoreboard: true
    # This part hides chunk seeds to prevent cheats from determining the exact location of structures.
    seed: true
    # This part hides the player's actual effects to prevent them from being displayed in PotionList or cheat Notifications.
    end_effect: true
    # This part hides potion effects to prevent cheats from showing the exact type and duration of effects.
    potion: true
    # This part hides player gamemode to prevent cheats from determining the current mode.
    gamemode: true
    # This part hides player ping to prevent cheats from showing the exact value.
    ping: true

    # Spectator settings (requires permission: darkness.spectator)
    spectators:
      # Only hide spectators in these worlds. Leave empty to allow all worlds
      allowed_worlds:
       - ""
      # Hide all spectators with darkness.spectator permission, regardless of activity.
      hide_spectators: true

# Should we eject players when they get close to flagging?
# It is suggested to leave this option enabled since it can sometimes help prevent issues such as desync
elytra_eject: true

# Should we eject players when get close inventory on flag?
# It is suggested to leave this option enabled since it can sometimes help prevent issues such as desync
inventory_eject: true

# Should the cinematic camera be taken into account?
# It is highly recommended not to enable this option, as it will make aim checks less effective.
# In a real combat scenario, none of the opponents will fight using a cinematic camera.
account_cinematic: false

# Enable logging plugins who have injected into netty on join to debug compatibility issues
debug_pipeline_on_join: false

# Enables experimental checks
experimental_checks: false

# A logger for monitoring packets sent by players, useful for developers.
packet_logger:
  enabled: false

  # Specify the players below whose packets will be logged to the console.
  whitelist:
    - 1hendex

  # List of packets to ignore.
  # To find the correct names, open the PacketEvents GitHub and look for the names.
  # Path: https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/packettype/PacketType.java
  ignore:
    - WINDOW_CONFIRMATION
    - KEEP_ALIVE
    - PONG

# The server name that will be shown in Player Logs and Discord Messages
server_name: Darkness Server

# Should we disable the bypass permission?
# If enabled, Darkness will check all players, including operators
# Disable this for some perfomance gain
disable_bypass_permission: false

# Darkness is able to enforce that a player set out of flying state cannot have more than X milliseconds of ping
# This is due to Darkness not currently checking flying players
max_ping_out_of_flying: 300

# Maximum ping when a firework boost is removed from the player.
# This prevents high latency players from being able to use 1 firework boost with an elytra forever.
max_ping_firework_boost: 1000

config:
  checks_updates: true
  lang: en
  version: 1
