# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                       Darkness Liquidation                                   |
# |                                                                                              |
# |                               Discord: https://dsc.gg/darkness-liquidation                   |
# |                                                                                              |
# |                                 Authors: 1hendex x clopdisabler                              |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# Для запуска Darkness требуется лицензия (предоставляется при покупке)
your_license: "null"

alerts:
  # Кроме трансляции оповещений игрокам, должны ли они также отправляться на консоль?
  print_to_console: true
  # Это контролирует, будут ли/как будут передаваться оповещения между серверами, подключенными к вашему прокси.
  # У вас должен быть включен 'bungee-plugin-message-channel' в конфигурации Velocity, если используется Velocity.
  proxy:
    # Следует ли отправлять оповещения на другие серверы, подключенные к вашему прокси-серверу?
    send: false
    # Должны ли оповещения, полученные с других серверов, быть объявлены на этом сервере?
    receive: false

verbose:
  print_to_console: false

# Включить ли тестовый режим?
# Если этот режим включён, команды наказания, вращения и перемешивания слотов не будут работать.
test_mode: false

# Client Settings
client_settings:

  # Client Alert Settings
  alert:

    # Должны ли мы отправлять предупреждение, когда игрок присоединяется, указывая его бренд клиента?
    enabled: true

    # Это означает, что он не будет транслировать свой бренд операторам, если бренд соответствует следующим регексам
    ignored_clients:
      - "^vanilla$"
      - "^fabric$"

  # Клиентские бренды, содержащие следующие название, будут заблокированы от входа на сервер
  banned_clients:
    - "^1.12.2$"
    - "^mcp$"
    - "^ForgeOptiFine 1.16.5/forge/modified$"
    - "Remix"
    - "CRYSTAL"
    - "matrix"
    - "CRYSTAL\\|6LAKS0TRIES"
    - "CrystalWare"
    - "RYSTAL\\|KZ1LM9TO"
    - "Misplace"
    - "reach"
    - "lmaohax"
    - "Reach Mod"
    - "cock"
    - "Vape v3"
    - "1946203560"
    - "#unbanearwax"
    - "EARWAXWASHERE"
    - "Cracked Vape"
    - "EROUAXWASHERE"
    - "moon:exempt"
    - "Vape"
    - "WDL\\|INIT"
    - "WDL\\|CONTROL"
    - "Bspkrs Client"

  # Максимальная/Минимальная длина имени бренда клиента
  brand_max_length: 26
  brand_min_length: 5
  # Блокировка использования недопустимых символов в имени бренда.
  block_illegal_symbol: true

# Сколько времени должно быть у игроков, пока мы не выкинем их за тайм-аут? По умолчанию = 60 секунд
max_transaction_time: 60

# Максимально допустимая задержка между транзакциями, при котором кикаем игрока в тайм-аут
# Срабатывает, при FreeCam, BackTrack, Blink
max_transaction_delay: 400

# Максимальное отрицательное время таймера, при котором кикаем игрока в тайм-аут
# Срабатывает, при Timer (0.1), Freeze
max_negative_time: 5000

# Настройки команд наказания // Не рекомендуется к использованию - скоро будет удалено
point_command:

  # Команды, которые будут выполняться при различных условиях (например, при нарушениях)
  '1': darkness rotate %PLAYER%
  '2': darkness shuffle %PLAYER% many
  '3': darkness rotate %PLAYER%
  '4': darkness shuffle %PLAYER% many
  '6': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '7': darkness crash %PLAYER% particle
  '8': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '9': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов
  '21': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '26': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '30': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов
  '34': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '38': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов

# Punish Command Settings
punish_command:

  # Какую анимацию наказания должна показывать Даркнесс перед киком игрока?
  # Анимации: NONE, THOR, FIRE, ERROR, RANDOM для выбора случайной анимации каждый раз
  animation: NONE

  # Должны ли мы отправлять сообщение в чат, когда игрок наказывается Даркнесс?
  broadcast: true

  # Какую команду должна выполнить Даркнесс после завершения анимации наказания? (%nl% для новой строки)
  # Плейсхолдеры: %prefix% -> (Префикс Даркнесс), %player% -> (Игрок, который был наказан), %reason% -> (Причина, указанная в команде наказания Даркнесс)
  command: darkness kick %player% %prefix% %reason%

# Ban Command Settings
ban_command:

  # Должны ли мы отправлять сообщение в чат, когда игрок наказывается Даркнесс?
  broadcast: true

  # Плейсхолдеры: %player% -> (Игрок, который был наказан), %reason% -> (Причина, указанная в команде наказания Даркнесс)
  command: ban %player% %reason%

# Discord Sync Settings
discord:

  # Вы хотите синхронизировать Даркнесс с вашим Discord-сервером?
  enabled: false
  # Вставьте URL вебхука канала
  webhook_url: ""
  # Заголовок сообщения
  embed_title: "**:fire: ОБНАРУЖЕН НОВЫЙ ЧИТЕР!**"
  # Цвет полосы слева от сообщения
  embed_color: "#ff0000"
  # Содержимое сообщения
  violation_content:
    - "%player%"
    - ""
    - "**Режим:**"
    - "%server_name%"
    - ""
    - "**Тип чита:**"
    - "%check%"
    - ""
    - "**Уровень:**"
    - "%violations%"
    - ""
    - "**Клиент:**"
    - "%brand%"
    - ""
    - "**Версия:**"
    - "%version%"
    - ""
    - "**PING | TPS:**"
    - "%ping% | %tps%"
  # Заголовок дополнительного поля в эмбеде
  embed_field: "Информация:"

# Log Settings
logs:

  # Какой тип логирования использовать Даркнесс?
  # Типы: NONE, OLD, NEW
  # - NONE: Отключает логирование полностью
  # - OLD: Логирует все флаги в один файл data.yml
  # - NEW: Логирует каждый день в отдельный файл внутри папки logs
  # Изменения применяются только после перезагрузки сервера.
  log_type: OLD

  # Нужно ли нам проверять лог на наличие старых и удалять их?
  clearing: true

  # Логи, старше этого значения в днях, будут удалены даркнесс
  clear_days: 7

## InformationHider Check
InformationHider:

  # Включить модуль скрытия информации?
  enabled: true

  # Проверять только игроков или всех сущностей?
  onlyForPlayers: true

  # Скрывает данные об игроках и мобах, чтобы чит-клиенты не могли получить лишнюю инфу.
  # На обычной игре это не заметно, но мешает читам.
  parts:
    # Спуфит здоровье — мобы и игроки всегда показывают фейковое здоровье
    # Полезно против хп-баров в модах и читах
    health:
      spoof: true  # Рекомендуется
      zero: false  # Фиксит множество KillAura, но, ломает анимации, не советуется
    # Прочее скрытие
    enchant: true         # Скрывает зачары
    item_count: true      # Кол-во предметов
    item_name: true       # Названия предметов
    durability: true      # Прочность предметов
    xp: true              # Опыт
    air: true             # Воздух
    absorption: true      # Поглощение
    saturation: true      # Насыщение
    scoreboard: true      # Скорборды
    seed: true            # Сид мира
    potion: true          # Эффекты
    gamemode: true        # Режим игры

    # Подменяет стаффов на фейковых игроков
    fake_staff:
      enabled: true
      bots: 60

    # Настройки зрителей (с permission: darkness.spectator)
    spectators:
      # В каких мирах скрывать. Пусто — во всех
      allowed_worlds:
        - ""
      # Скрывать всегда, даже если они ничего не делают
      hide_spectators: true

# Закрывать элитру у игрока при флаге?
# Рекомендуется оставить эту опцию включенной, так как она может помочь предотвратить такие проблемы, как десинхронизация
elytra_eject: true

# Закрывать инвентарь у игрока при флаге?
# Рекомендуется оставить эту опцию включенной, так как она может помочь предотвратить такие проблемы, как десинхронизация
inventory_eject: true

# Нужно ли учитывать кинематографическую камеру?
# Настоятельно рекомендуется не включать эту опцию, так как это сделает проверки аим менее эффективными
# В реальном боевом сценарии ни один из противников не будет сражаться, используя кинематографическую камеру
account_cinematic: false

# Включить запись в журнал плагинов, которые внедрились в netty при присоединении для отладки проблем совместимости
debug_pipeline_on_join: false

# Эта настройка применяется только к клиентам 1.17–1.20.5 на серверах 1.8
cancel_duplicate_packet: true

# Игнорировать ли ротацию в дублирующихся пакетах?
ignore_duplicate_packet_rotation: true

# Включает экспериментальные проверки
experimental_checks: false

# Логгер для просмотра пакетов которые кидают игроки, полезно для разработчиков
packet_logger:
  enabled: false

  # Укажите ниже игроков, у которых будут логироваться все пакеты в консоль
  whitelist:
    - 1hendex

  # Список пакетов, которые нужно игнорировать
  # Чтобы узнать правильные имена, откройте гитхаб PacketEvents и найдите имена
  # Путь: https://github.com/retrooper/packetevents/tree/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play
  ignore:
    - WINDOW_CONFIRMATION
    - KEEP_ALIVE
    - PONG

# Название сервера, которое будет отображаться в логах игроков и сообщениях Discord
server_name: Darkness Server

# Нужно ли включить шифрование команд Darkness?
# Отключите для исправления некоторых проблем с несовместимостью с другими античитами.
# Изменения применяются только после перезагрузки сервера.
enabled_command_obfuscation: true

# Стоит ли нам отключить разрешение на обход?
# Если включено, Даркнесс проверит всех игроков, включая операторов
# Отключите это для некоторого прироста производительности
disable_bypass_permission: false

# Даркнесс иногда отменяет незаконные пакеты, например, с таймером, после X пакетов в секунду отмененных, когда следует
# нам просто кикнуть игрока? Это необходимо, так как некоторые ограничители пакетов не учитывают пакеты, отмененные Даркнесс.
packet_spam_threshold: 100

# Даркнесс может обеспечить, что игрок, выведенный из состояния полёта, не может иметь пинг более X миллисекунд.
# Это связано с тем, что Даркнесс в настоящее время не проверяет летающих игроков.
max_ping_out_of_flying: 1000

# Максимальный пинг, когда усиление фейерверка снимается с игрока.
# Это не позволяет игрокам с высокой задержкой использовать 1 усиление фейерверка с надкрыльями навсегда.
max_ping_firework_boost: 1000

config:
  checks_updates: true
  lang: ru
  version: 1
