# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                       Darkness Liquidation                                   |
# |                                                                                              |
# |                               Discord: https://dsc.gg/darkness-liquidation                   |
# |                                                                                              |
# |                                 Authors: 1hendex x clopdisabler                              |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# Для запуску Darkness потрібна ліцензія (надається після покупки)
your_license: "null"

alerts:
  # Окрім трансляції сповіщень гравцям, чи повинні вони також надсилатися на консоль?
  print_to_console: true
  # Це контролює, чи будуть/як будуть передаватися сповіщення між серверами, підключеними до вашого проксі.
  # У вас має бути включений 'bungee-plugin-message-channel' у конфігурації Velocity, якщо використовується Velocity.
  proxy:
    # Чи слід надсилати сповіщення на інші сервери, підключені до вашого проксі-сервера?
    send: false
    # Чи повинні сповіщення, отримані з інших серверів, оголошуватися на цьому сервері?
    receive: false

verbose:
  print_to_console: false

# Чи потрібно увімкнути тестовий-режим?
# Якщо цей режим увімкнено, команди покарання, обертання та перемішування слотів не працюватимуть.
test_mode: false

# Client Settings
client_settings:

  # Client Alert Settings
  alert:

    # Должны ли мы отправлять предупреждение, когда игрок присоединяется, указывая его бренд клиента?
    enabled: true

    # Это означает, что он не будет транслировать свой бренд операторам, если бренд соответствует следующим регексам
    ignored_clients:
      - "^vanilla$"
      - "^fabric$"

  # Клієнтські бренди, що містять такі назви, будуть заблоковані від входу на сервер
  banned_clients:
    - "^1.12.2$"
    - "^mcp$"
    - "^ForgeOptiFine 1.16.5/forge/modified$"
    - "Remix"
    - "CRYSTAL"
    - "matrix"
    - "CRYSTAL\\|6LAKS0TRIES"
    - "CrystalWare"
    - "RYSTAL\\|KZ1LM9TO"
    - "Misplace"
    - "reach"
    - "lmaohax"
    - "Reach Mod"
    - "cock"
    - "Vape v3"
    - "1946203560"
    - "#unbanearwax"
    - "EARWAXWASHERE"
    - "Cracked Vape"
    - "EROUAXWASHERE"
    - "moon:exempt"
    - "Vape"
    - "WDL\\|INIT"
    - "WDL\\|CONTROL"
    - "Bspkrs Client"

  # Максимальна/Мінімальна довжина назви бренду клієнта
  brand_max_length: 26
  brand_min_length: 5
  # Блокування використання неприпустимих символів у назві бренду.
  block_illegal_symbol: true

# Скільки часу гравець має перед тим, як його викине за тайм-аут? За замовчуванням = 60 секунд
max_transaction_time: 60
# Максимально допустима затримка між транзакціями, після якої гравця кикне в тайм-аут
# Спрацьовує при FreeCam, BackTrack, Blink
max_transaction_delay: 400
# Максимальне від’ємне значення таймера, при якому гравця кикне в тайм-аут
# Спрацьовує при Timer (0.1), Freeze
max_negative_time: 5000

# Налаштування команд покарання // Не рекомендується до використання — скоро буде видалено
point_command:

  # Команди, які будуть виконуватися за різних умов (наприклад, при порушеннях)
  '1': darkness rotate %PLAYER%
  '2': darkness shuffle %PLAYER% many
  '3': darkness rotate %PLAYER%
  '4': darkness shuffle %PLAYER% many
  '6': darkness kick %PLAYER% &cПідозра у використанні читів
  '7': darkness crash %PLAYER% particle
  '8': darkness kick %PLAYER% &cПідозра у використанні читів
  '9': darkness ban %PLAYER% &cПідозра у використанні читів
  '21': darkness kick %PLAYER% &cПідозра у використанні читів
  '26': darkness kick %PLAYER% &cПідозра у використанні читів
  '30': darkness ban %PLAYER% &cПідозра у використанні читів
  '34': darkness kick %PLAYER% &cПідозра у використанні читів
  '38': darkness ban %PLAYER% &cПідозра у використанні читів

# Punish Command Settings
punish_command:

  # Яку анімацію покарання повинна показувати Даркнесс перед киком гравця?
  # Анімації: NONE, THOR, FIRE, ERROR, RANDOM для вибору випадкової анімації кожен раз
  animation: NONE

  # Чи повинні ми надсилати повідомлення в чат, коли гравець карається Даркнесс?
  broadcast: true

  # Яку команду повинна виконати Даркнесс після завершення анімації покарання? (%nl% для нового рядка)
  # Плейсхолдери: %prefix% -> (Префікс Даркнесс), %player% -> (Гравець, який був покараний), %reason% -> (Причина, вказана в команді покарання Даркнесс)
  command: darkness kick %player% %prefix% %reason%

# Ban Command Settings
ban_command:

  # Чи повинні ми надсилати повідомлення в чат, коли гравець карається Даркнесс?
  broadcast: true

  # Плейсхолдери: %player% -> (Гравець, який був покараний), %reason% -> (Причина, вказана в команді покарання Даркнесс)
  command: ban %player% %reason%

# Discord Sync Settings
discord:

  # Ви хочете синхронізувати Darkness із вашим Discord-сервером?
  enabled: false
  # Вставте URL вебхука каналу
  webhook_url: ""
  # Заголовок повідомлення
  embed_title: "**:fire: ВИЯВЛЕНО НОВОГО ЧІТЕРА!**"
  # Колір смуги зліва від повідомлення
  embed_color: "#ff0000"
  # Зміст повідомлення
  violation_content:
    - "%player%"
    - ""
    - "**Режим:**"
    - "%server_name%"
    - ""
    - "**Тип чіту:**"
    - "%check%"
    - ""
    - "**Рівень:**"
    - "%violations%"
    - ""
    - "**Клієнт:**"
    - "%brand%"
    - ""
    - "**Версія:**"
    - "%version%"
    - ""
    - "**PING | TPS:**"
    - "%ping% | %tps%"
  # Заголовок додаткового поля в ембед
  embed_field: "Інформація:"

# Log Settings
logs:

  # Який тип логування використовувати Darkness?
  # Типи: NONE, OLD, NEW
  # - NONE: Повністю вимикає логування
  # - OLD: Логує всі флаги в один файл data.yml
  # - NEW: Логує кожен день в окремий файл у папці logs
  # Зміни застосовуються лише після перезавантаження сервера.
  log_type: OLD

  # Чи потрібно перевіряти лог на наявність старих і видаляти їх?
  clearing: true

  # Логи, старші за це значення в днях, будуть видалені
  clear_days: 7

## InformationHider Check
InformationHider:

  # Увімкнути модуль приховування інформації?
  enabled: true

  # Перевіряти тільки гравців чи всіх істот?
  onlyForPlayers: true

  # Приховує дані про гравців та мобів, щоб чити не могли отримати зайву інформацію.
  # Для звичайних гравців нічого не зміниться, але чити не працюватимуть як треба.
  parts:
    # Спуфить здоров’я — гравці та моби завжди показують фейкове здоровья
    # Корисно проти хп-барів у модах та читах
    health:
       spoof: true  # Рекомендовано
       zero: false  # Ламає багато KillAura, але й анімації — не радимо вмикати

    # Інше приховування
    enchant: true         # Зачарування
    item_count: true      # Кількість предметів
    item_name: true       # Назви предметів
    durability: true      # Міцність предметів
    xp: true              # Досвід
    air: true             # Кисень
    absorption: true      # Поглинання
    saturation: true      # Насичення
    scoreboard: true      # Скорборд
    seed: true            # Сід світу
    potion: true          # Ефекти
    gamemode: true        # Режим гри

    # Підмінює стафф на фейкових гравців
    fake_staff:
      enabled: true
      bots: 60

    # Налаштування глядачів (потрібен дозвіл: darkness.spectator)
    spectators:
      # В яких світах ховати. Порожній список — усі світи
      allowed_worlds:
        - ""
      # Ховати завжди, навіть якщо просто стоять
      hide_spectators: true

# Закривати елітру у гравця при флазі?
# Рекомендується залишити цю опцію ввімкненою, оскільки вона може допомогти запобігти таким проблемам, як десинхронізація
elytra_eject: true

# Закривати інвентар у гравця при флазі?
# Рекомендується залишити цю опцію ввімкненою, оскільки вона може допомогти запобігти таким проблемам, як десинхронізація
inventory_eject: true

# Чи потрібно враховувати кінематографічну камеру?
# Настійно рекомендується не вмикати цю опцію, оскільки це зробить перевірки прицілювання менш ефективними.
# У реальному бойовому сценарії жоден із супротивників не буде битися, використовуючи кінематографічну камеру.
account_cinematic: false

# Увімкнути запис у журнал плагінів, які впроваджені в netty при підключенні для налагодження проблем сумісності
debug_pipeline_on_join: false

# Цей параметр застосовується лише до клієнтів 1.17–1.20.5 на серверах 1.8
cancel_duplicate_packet: true

# Ігнорувати ротацію в дублюючих пакетах?
ignore_duplicate_packet_rotation: true

# Увімкнути експериментальні перевірки
experimental_checks: false

# Логер для перегляду пакетів, які надсилають гравці, корисно для розробників.
packet_logger:
  enabled: false

  # Вкажіть нижче гравців, чиї пакети будуть логуватися в консолі.
  whitelist:
    - 1hendex

  # Список пакетів, які потрібно ігнорувати.
  # Щоб дізнатися правильні імена, відкрийте GitHub PacketEvents і знайдіть назви.
  # Шлях: https://github.com/retrooper/packetevents/tree/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play
  ignore:
    - WINDOW_CONFIRMATION
    - KEEP_ALIVE
    - PONG

# Назва сервера, яка буде відображатися в логах гравців та повідомленнях Discord
server_name: Darkness Server

# Чи потрібно ввімкнути шифрування команд Darkness?
# Вимкніть, щоб уникнути проблем із несумісністю з іншими античитами.
# Зміни застосовуються лише після перезавантаження сервера.
enabled_command_obfuscation: true

# Чи слід нам вимкнути дозвіл на обход?
# Якщо ввімкнено, Даркнесс перевірятиме всіх гравців, включаючи операторів
# Вимкніть це для покращення продуктивності
disable_bypass_permission: false

# Даркнесс іноді скасовує незаконні пакети, наприклад, з таймером, після X пакетів на секунду, скасованих, коли слід
# нам просто вигнати гравця? Це необхідно, оскільки деякі обмежувачі пакетів не враховують пакети, скасовані Даркнесс.
packet_spam_threshold: 100

# Даркнесс може гарантувати, що гравець, виведений з режиму польоту, не може мати пінг більше X мілісекунд.
# Це пов'язано з тим, що Даркнесс наразі не перевіряє літаючих гравців.
max_ping_out_of_flying: 1000

# Максимальний пінг, коли посилення феєрверка знімається з гравця.
# Це не дозволяє гравцям із високою затримкою використовувати одне посилення феєрверка з надкриллями назавжди.
max_ping_firework_boost: 1000

config:
  checks_updates: true
  lang: uk
  version: 1
